import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
// import Navbar from "@/components/V1/nav1";
import Nav1 from "@/components/V1/nav1";
// import Nav1 from "@/components/V0/navbar";
// import Navbar from "@/components/V0/navbar";
import Footer from "@/components/V1/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preconnect and preload for LCP video */}
        <link rel="preconnect" href="https://dwp-front.vercel.app" crossOrigin="anonymous" />
        <link rel="preload" as="video" href="https://dwp-front.vercel.app/dwp-video.webm" type="video/mp4" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        <Nav1 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
